# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d78ec7856d7693dc7b7ef995aef55576e54b9e060284bd14fff46567fd4e0d5a11371dedb68df87add3ea223e1a50f4586207824043e2156148f5df2693c01c7

test:
  secret_key_base: 3456b74f1265e4a2fbf243f89dc4bdc20fcfacaeed587532d0f56ede4297244c63372b63ce4cad59e3001f9d66d05ab92c5c6c6d64551a392e046955a60d1988

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
